/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: scores.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "scores.pb-c.h"
void   player_score__init
                     (PlayerScore         *message)
{
  static const PlayerScore init_value = PLAYER_SCORE__INIT;
  *message = init_value;
}
size_t player_score__get_packed_size
                     (const PlayerScore *message)
{
  assert(message->base.descriptor == &player_score__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t player_score__pack
                     (const PlayerScore *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &player_score__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t player_score__pack_to_buffer
                     (const PlayerScore *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &player_score__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PlayerScore *
       player_score__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PlayerScore *)
     protobuf_c_message_unpack (&player_score__descriptor,
                                allocator, len, data);
}
void   player_score__free_unpacked
                     (PlayerScore *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &player_score__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   score_update__init
                     (ScoreUpdate         *message)
{
  static const ScoreUpdate init_value = SCORE_UPDATE__INIT;
  *message = init_value;
}
size_t score_update__get_packed_size
                     (const ScoreUpdate *message)
{
  assert(message->base.descriptor == &score_update__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t score_update__pack
                     (const ScoreUpdate *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &score_update__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t score_update__pack_to_buffer
                     (const ScoreUpdate *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &score_update__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScoreUpdate *
       score_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScoreUpdate *)
     protobuf_c_message_unpack (&score_update__descriptor,
                                allocator, len, data);
}
void   score_update__free_unpacked
                     (ScoreUpdate *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &score_update__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor player_score__field_descriptors[2] =
{
  {
    "player_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PlayerScore, player_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PlayerScore, score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned player_score__field_indices_by_name[] = {
  0,   /* field[0] = player_id */
  1,   /* field[1] = score */
};
static const ProtobufCIntRange player_score__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor player_score__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PlayerScore",
  "PlayerScore",
  "PlayerScore",
  "",
  sizeof(PlayerScore),
  2,
  player_score__field_descriptors,
  player_score__field_indices_by_name,
  1,  player_score__number_ranges,
  (ProtobufCMessageInit) player_score__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor score_update__field_descriptors[2] =
{
  {
    "scores",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ScoreUpdate, n_scores),
    offsetof(ScoreUpdate, scores),
    &player_score__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "game_over",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScoreUpdate, game_over),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned score_update__field_indices_by_name[] = {
  1,   /* field[1] = game_over */
  0,   /* field[0] = scores */
};
static const ProtobufCIntRange score_update__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor score_update__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ScoreUpdate",
  "ScoreUpdate",
  "ScoreUpdate",
  "",
  sizeof(ScoreUpdate),
  2,
  score_update__field_descriptors,
  score_update__field_indices_by_name,
  1,  score_update__number_ranges,
  (ProtobufCMessageInit) score_update__init,
  NULL,NULL,NULL    /* reserved[123] */
};
