# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scores.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scores.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cscores.proto\"/\n\x0bPlayerScore\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x05\"+\n\x0bScoreUpdate\x12\x1c\n\x06scores\x18\x01 \x03(\x0b\x32\x0c.PlayerScoreb\x06proto3'
)




_PLAYERSCORE = _descriptor.Descriptor(
  name='PlayerScore',
  full_name='PlayerScore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_id', full_name='PlayerScore.player_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='PlayerScore.score', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=63,
)


_SCOREUPDATE = _descriptor.Descriptor(
  name='ScoreUpdate',
  full_name='ScoreUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='scores', full_name='ScoreUpdate.scores', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=108,
)

_SCOREUPDATE.fields_by_name['scores'].message_type = _PLAYERSCORE
DESCRIPTOR.message_types_by_name['PlayerScore'] = _PLAYERSCORE
DESCRIPTOR.message_types_by_name['ScoreUpdate'] = _SCOREUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerScore = _reflection.GeneratedProtocolMessageType('PlayerScore', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERSCORE,
  '__module__' : 'scores_pb2'
  # @@protoc_insertion_point(class_scope:PlayerScore)
  })
_sym_db.RegisterMessage(PlayerScore)

ScoreUpdate = _reflection.GeneratedProtocolMessageType('ScoreUpdate', (_message.Message,), {
  'DESCRIPTOR' : _SCOREUPDATE,
  '__module__' : 'scores_pb2'
  # @@protoc_insertion_point(class_scope:ScoreUpdate)
  })
_sym_db.RegisterMessage(ScoreUpdate)


# @@protoc_insertion_point(module_scope)
